"""add models

Revision ID: b9b0d48ef7ab
Revises: e1a0f6931ec6
Create Date: 2023-08-08 16:14:33.579332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9b0d48ef7ab'
down_revision = 'e1a0f6931ec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title_uz', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('title_ru', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('title_en', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='word_pkey')
    )
    # ### end Alembic commands ###
