"""add models

Revision ID: e1a0f6931ec6
Revises: 1cb4599be8c3
Create Date: 2023-08-08 16:10:53.897941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1a0f6931ec6'
down_revision = '1cb4599be8c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_uz', sa.String(), nullable=True),
    sa.Column('title_ru', sa.String(), nullable=True),
    sa.Column('title_en', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('question')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='question_pkey')
    )
    op.drop_table('word')
    # ### end Alembic commands ###
